name: load-lite Test

on:
  pull_request:
    branches: ["main"]

jobs:
  dev-server-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build code
        run: go build -o load-lite ./main.go

      - name: Run load-lite test Google
        run: |
          ./load-lite \
            --url https://www.google.com \
            --method GET \
            --rps 2 \
            --duration 2
